--->Thread safe . ####
--create app using MVP ####
--dagger 2 ####
--depandancy injections ####
--knif ####
--UI/develop best Pracrices #####
--how to develope buteful UI ####
--->abstraction is the theory and dependencies are the practice. #####
--Spring Template or Volley #### 
--->Activity Classes for Dependency inversion ####
--->Dependency Injection  ####
--->MemoryLeaks  #####
--->Spring Template or Volley   #####
--->Butter knife or RoboGuice or Dagger 2 #####
--->Recycler cursur adapter ####

--->Data Binding liberary 
--->RoboGuice
--->AndroidAnnotatios
--apply Broadcast Reciver
--Read design pattern book
--learn fireBase
--apply project in fire base
--Bit Map Programming 
--GCM 
--Web Sockets 
--Eventbus 
--PubNub 
--Recycler cursur adapter
